name: SwagLabs Test Automation

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run SwagLabs Selenium Tests
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.test-status.outputs.result }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Chrome Browser
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Verify Environment
        run: |
          java -version
          mvn -version
          google-chrome --version
          chromedriver --version

      - name: Clean and Compile
        run: |
          mvn clean
          mvn compile test-compile

      - name: Run SwagLabs Tests
        continue-on-error: true
        run: mvn test -Dheadless=true
        env:
          CHROME_OPTIONS: --headless --no-sandbox --disable-dev-shm-usage --window-size=1920,1080

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-${{ github.run_number }}
          path: |
            allure-results/
            target/site/allure-maven-plugin/
          retention-days: 30

      - name: Upload Surefire Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports-${{ github.run_number }}
          path: target/surefire-reports/
          retention-days: 30

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure-screenshots-${{ github.run_number }}
          path: screenshots/
          retention-days: 7

      - name: Evaluate Test Results
        id: test-status
        if: always()
        run: |
          FAILURES=$(grep -c "<failure" target/surefire-reports/TEST-*.xml || true)
          ERRORS=$(grep -c "<error" target/surefire-reports/TEST-*.xml || true)
          if [ "$FAILURES" -gt 0 ] || [ "$ERRORS" -gt 0 ]; then
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "result=success" >> $GITHUB_OUTPUT
          fi

      - name: Fail Job if Tests Failed
        if: steps.test-status.outputs.result == 'failure'
        run: exit 1

      - name: Generate Test Summary
        if: always()
        run: |
          echo "## SwagLabs Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Number:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Runner:** ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ steps.test-status.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f target/surefire-reports/TEST-*.xml ]; then
            TESTS=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -l "testcase" {} \; | wc -l)
            echo "- **Test Classes:** $TESTS" >> $GITHUB_STEP_SUMMARY
          fi

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.test.outputs.result }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: |
            SwagLabs Tests ${{ needs.test.outputs.result == 'success' && '✅ PASSED' || '❌ FAILED' }}

            Test Details:
            • Repository: ${{ github.repository }}
            • Branch: ${{ github.ref_name }}
            • Commit: ${{ github.sha }}
            • Author: ${{ github.actor }}
            • Workflow: ${{ github.workflow }}

            View Results: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
