name: SwagLabs Test Automation

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run SwagLabs Selenium Tests
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.test-status.outputs.result }}

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Install Chrome and ChromeDriver
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      # Verify Environment
      - name: Verify Environment
        run: |
          java -version
          mvn -version
          google-chrome --version
          chromedriver --version

      # Clean, compile, and test
      - name: Clean and Compile
        run: |
          mvn clean
          mvn compile test-compile

      # Run tests (allow failures to continue)
      - name: Run SwagLabs Tests
        continue-on-error: true
        run: mvn test -Dheadless=true -Dbrowser=chrome
        env:
          CHROME_OPTIONS: "--headless=new --no-sandbox --disable-dev-shm-usage --window-size=1920,1080"

      # Install Allure CLI for report generation
      - name: Install Allure CLI
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -xvzf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      # Upload Allure Report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-${{ github.run_number }}
          path: allure-report/
          retention-days: 30

      # Upload Surefire test results
      - name: Upload Surefire Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-reports-${{ github.run_number }}
          path: target/surefire-reports/
          retention-days: 30

      # Upload Screenshots if tests fail
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure-screenshots-${{ github.run_number }}
          path: screenshots/
          retention-days: 7

      # Extract failing tests from Surefire reports
      - name: Extract Failing Tests
        id: extract-failures
        if: failure()
        run: |
          echo "FAILURES<<EOF" >> $GITHUB_ENV
          grep -h "<testcase" target/surefire-reports/*.xml | grep -B1 "<failure" | grep "classname" | sed -E 's/.*classname="([^"]+)".*name="([^"]+)".*/- \1.\2/' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Evaluate the test results and determine if the tests passed or failed
      - name: Evaluate Test Results
        id: test-status
        if: always()
        run: |
          FAILURES=$(grep -c "<failure" target/surefire-reports/TEST-*.xml || true)
          ERRORS=$(grep -c "<error" target/surefire-reports/TEST-*.xml || true)
          if [ "$FAILURES" -gt 0 ] || [ "$ERRORS" -gt 0 ]; then
            echo "result=failure" >> $GITHUB_OUTPUT
          else
            echo "result=success" >> $GITHUB_OUTPUT
          fi

      # Generate test summary in GitHub Actions UI
      - name: Generate Test Summary
        if: always()
        run: |
          echo "## SwagLabs Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Number:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status:** ${{ steps.test-status.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Actor:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY

  # Notify via Slack about test results
  notify:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Send Slack Message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ needs.test.outputs.result }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: |
            🧪 *SwagLabs Tests — ${{ needs.test.outputs.result == 'success' && '✅ PASSED' || '❌ FAILED' }}*

            • Repo: `${{ github.repository }}`
            • Branch: `${{ github.ref_name }}`
            • Commit: `${{ github.sha }}`
            • Author: `${{ github.actor }}`
            • Workflow: `${{ github.workflow }}`

            ${{ env.FAILURES }}

            🔗 *[View CI Report →](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})*
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
